display_name: GektusClashX

packager: GektusVPN
packagerEmail: noreply@github.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - GektusClashX
  - Clash
    - Proxy

generic_name: GektusClashX

group: Applications/Internet

startup_notify: true
