display_name: GektusClashX

icon: ./assets/images/icon.png

keywords:
  - GektusClashX
  - Clash
  - ClashMeta
  - Proxy

generic_name: GektusClashX

categories:
  - Network

startup_notify: true

include: []