// GENERATED by setup.dart from core/go.mod — do not edit by hand
// ignore_for_file: constant_identifier_names

/// Embedded mihomo version (see core/go.mod).
const String kCoreVersionFromSource = 'v1.19.30';
