display_name: GektusClashX
package_name: GektusClashX
maintainer:
  name: GektusVPN
  email: noreply@github.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - GektusClashX
  - Clash
  - ClashMeta
  - Proxy

generic_name: GektusClashX

categories:
  - Network

startup_notify: true
