script_template: inno_setup.iss
app_id: EE50BAE7-23E9-4BD7-9ACA-780E5B15BF97
app_name: GektusClashX
publisher: GektusVPN
publisher_url: https://github.com/gektusvpn/GektusClashX
display_name: GektusClashX
executable_name: GektusClashX.exe
output_base_file_name: GektusClashX.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin
